apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: color-reduction-with-pca
  description: Color reduction with PCA
spec:
  type: website
  lifecycle: experimental
  owner: elemarjr
  system: labs
  tags:
    - react
    - tailwind
    - vite